#!/data/data/com.termux/files/usr/bin/bash
set -e

if [ "$1" = "configure" ];then
    tar -Jxf ~/.termux/MonoFonts.tar.xz -C ~/.termux
   [ -d ~/.oh-my-zsh/.git ] || tar -Jxf ~/.oh-my-zsh/omz-git.tar.xz -C ~/.oh-my-zsh
    t-init
    termux-reload-settings
    chsh -s zsh
    echo "您可能需要重启Termux才能完整应用软键盘(You may need to restart Termux to fully apply the softkeys)"
fi

